version : '2'
services:

  springappserver:
    build:
      context: .
      dockerfile: springapp.dockerfile
    restart: always
    container_name: springboot
    ports:
     - "8080:8080"
    volumes:
     - .:/vol/development
    depends_on:
     - mongodb

  mongodb:
    image: mongo
    container_name: springboot-mongo
    ports:
     - "27017:27017"
    volumes:
     - $HOME/data/springboot-mongo-data:/data/db
     - $HOME/data/springboot-mongo-bkp:/data/bkp
    restart: always
